apiVersion: v1
kind: Service
metadata:
  name: alnicos-loadbalancer
  labels: 
    app: alnicos
spec:
  type: LoadBalancer
  selector:
    app: alnicos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080